/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SewTestPlannung;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    public String getChrisIsDa(){
        return "Jojo whots poppin";
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getChrisIsDa());
    }
}
